CREATE TABLE report_table (
    id INT IDENTITY(1,1) PRIMARY KEY,
    menu NVARCHAR(255),
    sub_menu NVARCHAR(255),
    report_name NVARCHAR(255),
    report_query NVARCHAR(MAX),
    filter1 NVARCHAR(255),
    filter1_type NVARCHAR(100),
    filter2 NVARCHAR(255),
    filter2_type NVARCHAR(100),
    filter3 NVARCHAR(255),
    filter3_type NVARCHAR(100),
    filter4 NVARCHAR(255),
    filter4_type NVARCHAR(100),
    filter5 NVARCHAR(255),
    filter5_type NVARCHAR(100),
    filter6 NVARCHAR(255),
    filter6_type NVARCHAR(100),
    filter7 NVARCHAR(255),
    filter7_type NVARCHAR(100),
    filter8 NVARCHAR(255),
    filter8_type NVARCHAR(100),
    filter9 NVARCHAR(255),
    filter9_type NVARCHAR(100),
    filter10 NVARCHAR(255),
    filter10_type NVARCHAR(100)
);

INSERT INTO [dbo].[report_table] (
    [menu],
    [sub_menu],
    [report_name],
    [report_query],
    [filter1],
    [filter1_type],
    [filter2],
    [filter2_type],
    [filter3],
    [filter3_type],
    [filter4],
    [filter4_type],
    [filter5],
    [filter5_type],
    [filter6],
    [filter6_type],
    [filter7],
    [filter7_type],
    [filter8],
    [filter8_type],
    [filter9],
    [filter9_type],
    [filter10],
    [filter10_type]
) VALUES (
    'pickslips',
    'pending pickslips',
    'Order analaysis',
    'SELECT * FROM order_master,
    'pickslip_number',
    'dropdown',
    'item_code',
    'dropdown',
    'customer_name',
    'dropdown',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
);